"""Initial migration

Revision ID: 1e2d9efef6c5
Revises: 
Create Date: 2025-08-16 05:43:51.217896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e2d9efef6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('extracted_images', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_data_filename'), 'ocr_data', ['filename'], unique=False)
    op.create_index(op.f('ix_ocr_data_id'), 'ocr_data', ['id'], unique=False)
    op.drop_index('ix_images_id', table_name='images')
    op.drop_index('ix_images_upload_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.add_column('pricing_plans', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('pricing_plans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('uploads', sa.Column('file_name', sa.String(), nullable=False))
    op.add_column('uploads', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('xml_path', sa.String(), nullable=True))
    op.add_column('uploads', sa.Column('is_xml_valid', sa.Boolean(), nullable=True))
    op.add_column('uploads', sa.Column('html_path', sa.String(), nullable=True))
    op.add_column('uploads', sa.Column('epub_path', sa.String(), nullable=True))
    op.add_column('uploads', sa.Column('mobi_path', sa.String(), nullable=True))
    op.add_column('uploads', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('formula_count', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('processing_time', sa.Float(), nullable=True))
    op.add_column('uploads', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('uploads', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('uploads', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('uploads_id_seq'::regclass)"))
    op.alter_column('uploads', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               nullable=True)
    op.drop_column('uploads', 'extracted_text')
    op.drop_column('uploads', 'filename')
    op.drop_column('uploads', 'uploaded_at')
    op.drop_column('uploads', 'extracted_json')
    op.drop_column('uploads', 'processed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('uploads', sa.Column('extracted_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uploads', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('uploads', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('uploads', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('uploads', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               nullable=False)
    op.alter_column('uploads', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('uploads_id_seq'::regclass)"))
    op.drop_column('uploads', 'updated_at')
    op.drop_column('uploads', 'created_at')
    op.drop_column('uploads', 'error_message')
    op.drop_column('uploads', 'processing_time')
    op.drop_column('uploads', 'formula_count')
    op.drop_column('uploads', 'image_count')
    op.drop_column('uploads', 'page_count')
    op.drop_column('uploads', 'mobi_path')
    op.drop_column('uploads', 'epub_path')
    op.drop_column('uploads', 'html_path')
    op.drop_column('uploads', 'is_xml_valid')
    op.drop_column('uploads', 'xml_path')
    op.drop_column('uploads', 'file_size')
    op.drop_column('uploads', 'file_name')
    op.drop_column('pricing_plans', 'updated_at')
    op.drop_column('pricing_plans', 'created_at')
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], name='subscriptions_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name='images_upload_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_upload_id', 'images', ['upload_id'], unique=False)
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.drop_index(op.f('ix_ocr_data_id'), table_name='ocr_data')
    op.drop_index(op.f('ix_ocr_data_filename'), table_name='ocr_data')
    op.drop_table('ocr_data')
    # ### end Alembic commands ###